logging:
  config: classpath:logback.xml
server:
  port: 8088
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://localhost:8089/xxl-job-admin
    executor:
      appname: testApp
      ip:
      logpath: ./log/jobhandler
      logretentiondays: 20
      port: 9998